### ISSUE TITLE
meter registration not using api token from attributes

### ISSUE THREAD

**Issue by xrl** [boundary/boundary-meter_cookbook#6]
I am experiencing a failure bootstrapping a node because the `boundary-meter -l create` command is failing. The API token is not be set in the command:

```
boundary-meter -l create -L https://api.boundary.com -p : -b /etc/boundary -n tls://collector.boundary.com:4740 --nodename my-node --tag my-tag
STDOUT: 
STDERR: [provisio: 0747,provision_perfor] Insufficient credentials to provision the meter for enterprise or premium APIs
[provisio: 0788,provision_perfor] problem provisioning meter
```

See the `-p : `? That's the issue. If I run the command again and copy/paste my token it works.

My wrapper cookbook attributes:

```
default['boundary_meter']['token'] = 'api.snipsnip-snip'
default['boundary_meter']['hostname'] = "#{node.chef_environment}-#{node.name}"
```

and at the bottom of my wrapper cookbook `recipes/default.rb`:

```
include_recipe "boundary-meter"
```

I'm trying to go through the cookbook code but the issue is not jumping out at me.

**Comment by sigil66** [comment]
I cannot reproduce your issue. Can you try using the cookbook without wrapping it?

Based on your output it looks as if node.chef_environment is not coming across either.

**Comment by sigil66** [comment]
No response, closing.
